# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 298f30698a24ce098cc8f5c448127d29a0d384f4f79348958d381430c9b86461f54ef16f52b7124369b1de82f1a98605fbfb92f3c477724bd2ec552e39e4787f

test:
  secret_key_base: 1003b7b90ca589072076f227caebbc6e66d514dea97a8e9e51f0106bf761514e0b5b950024e2341947b837c725ac154a001ad434626a11163ca80b59b25e1d91

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
